version: "3"

services:
  mysql:
    image: arm64v8/mysql:8.4.0
    ports:
      - "3306:3306" # External port 3306 mapped to internal port 3306
    environment:
      MYSQL_ROOT_PASSWORD: "tranminhhuyen123@"
      MYSQL_DATABASE: vdt
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ptranminhhuyen123@",
        ]
      interval: 20s
      timeout: 5s
      retries: 4

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./backend/config.env
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql-data: